---
name: PocketAI
author: XenialDan
version: 0.19.0
main: xenialdan\PocketAI\Loader
api: [3.0.0, 4.0.0]
# Changes:
# 0.7.0: bumped to 4.0.0+dev
# 0.8.0: Added component classes
# 0.9.0: Fixed component classes & added missing classes
# 0.9.2: Added debugging tests
# 0.10.0: Start using pre-cached components
# 0.10.1: Use BaseComponent->apply(Entity)
# 0.10.2: Clean up Events & EntityProperties
# 0.10.3: Add back active component groups
# 0.11.0: Extend components & multi-components support
# 0.12.0: Change component tests to instanceof BaseTest
# 0.12.1: Extend BaseTest with operator and subject test, implement has_equipment and is_family tests
# 0.13.0: Rename BaseTest to BaseFilter, move filters into /filter
# 0.13.1: Move definitions into /definition
# 0.14.0: Add interfaces IEvent and IDefinition
# 0.15.0: Add BaseTrigger class
# 0.15.1: Use Filters class in InventoryEventListener
# 0.15.2: Change $filters to instanceof Filters
# 0.15.3: Improve leashing
# 0.16.0: Implement basic movement
# 0.17.0: Nuke alot of code, Add new component types, add AIManager
# 0.18.0: Build navigation & pathfinding tests
# 0.19.0: Use SalmonDE's Pathfinding virion
...
